###
GET http://localhost:8080/albarragan-ganegrin-juanfbrinezg/nombre/albarragan

###
GET http://localhost:8080/albarragan-ganegrin-juanfbrinezg/nombre/ganegrin

###
GET http://localhost:8080/albarragan-ganegrin-juanfbrinezg/nombre/juanfbrinezg

###
GET http://localhost:8081/nombre/albarragan

###
GET http://localhost:8081/nombre/ganegrin

###
GET http://localhost:8081/nombre/juanfbrinezg

###
GET http://localhost:8081/actuator/health

###
GET http://localhost:8081/actuator/info

###
GET http://localhost:8081/actuator/env

###
GET http://localhost:8081/actuator/metrics