server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        enabled: true
        native:
          search-locations:
          - classpath:/config

  profiles:
    active: native

eureka:
  client:
    registerWithEureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:9988/eureka/}
  instance:
    prefer-ip-address: true
